version: '3.9'

services:
  dctools:
    env_file:
        ".env"
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "gdesmarais/dctools"
    ports:
      - "3000:3000"
    restart: unless-stopped      